//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/business-people-office-buildinggt.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/coury.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/degree.jpg")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/design-background5%20copy.jpg")]


